// ==============================================================================
// AI KARMAYOGI — MULTILINGUAL CONTEXT PROVIDER (BHASHINI INDIC TRANSLATIONS)
// Real-time language switching across Eighth Schedule Indian Languages
// ==============================================================================

import React, { createContext, useContext, useEffect, useState } from 'react';

export type SupportedLanguage =
  | 'en'
  | 'hi'
  | 'ta'
  | 'te'
  | 'bn'
  | 'mr'
  | 'gu'
  | 'kn'
  | 'ml'
  | 'pa'
  | 'or'
  | 'as';

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, fallback?: string) => string;
}

// ==============================================================================
// SOVEREIGN CIVIL SERVICES TRANSLATION DICTIONARY
// ==============================================================================
const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Top & Brand
    'brand.name': 'AI Karmayogi',
    'brand.sub': 'Mission Karmayogi Bharat',
    'brand.motto': 'Satyamev Jayate • Government of India',
    'brand.ministry': 'Ministry of Personnel, Public Grievances and Pensions',
    'brand.portal_badge': 'Mission Karmayogi Bharat Sovereign Portal',
    'brand.hero_desc': 'Accelerating competency diagnostic frameworks, personalized learning pathways, and adaptive civil service readiness powered by sovereign AI intelligence.',
    'brand.reach': 'Reach',
    'brand.officers_assessed': 'Officers Onboarded & Assessed',
    'brand.federal': 'Federal',
    'brand.ministries_count': 'Ministries & State Departments',
    'brand.models': 'Models',
    'brand.frameworks_count': 'Core Competency Frameworks',

    // Navigation
    'nav.overview': 'Overview',
    'nav.assessments': 'Assessments',
    'nav.recommendations': 'Recommendations',
    'nav.learning_path': 'Learning Path',
    'nav.trainer_studio': 'Trainer Studio',
    'nav.certificates': 'Certificates',
    'nav.admin_analytics': 'Admin Analytics',
    'nav.profile': 'Profile',
    'nav.sign_in': 'Sign In',
    'nav.register': 'Register',
    'nav.sign_out': 'Sign Out',
    'nav.demo_mode': 'Demo Mode',
    'nav.my_certificates': 'My Verifiable Certificates',
    'nav.cadre_analytics': 'Cadre Analytics Dashboard',
    'nav.officer_profile': 'Officer Profile & Security',

    // Login Form
    'login.title': 'Sign in to your account',
    'login.subtitle': 'Enter your official government email to access competency diagnostics',
    'login.email_label': 'Official Government Email',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in verified',
    'login.password_label': 'Password',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'Forgot password?',
    'login.submit_btn': 'Sign In to Karmayogi →',
    'login.no_account': "Don't have an official account?",
    'login.register_officer': 'Register as Officer',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-Click Auth',
    'login.civil_officer': 'Civil Officer',
    'login.learner': 'Learner',
    'login.faculty': 'Faculty',
    'login.trainer': 'Trainer',
    'login.director': 'Director',
    'login.admin': 'Admin',
    'login.sovereign_footer': 'Sovereign Local Self-Hosted Infrastructure • MeitY & Digital India Certified',
    'login.portal_tag': 'Civil Services Portal',
    'login.tier_iv': 'TIER-IV DATA CENTRE',
    'login.nic_powered': 'Powered by National Informatics Centre (NIC) Sovereign Compute Cluster',

    // Overview & Dashboard
    'overview.badge': 'Mission Karmayogi Bharat Sovereign Portal',
    'overview.hero_title': 'AI-Enabled Competency Diagnostic & Learning Ecosystem',
    'overview.hero_desc': 'Diagnosing civil service competency gaps, aligning role-based training via the iGOT Karmayogi repository, and delivering automated assessment generation for modern Indian governance.',
    'overview.sign_in_portal': 'Sign In to Portal',
    'overview.register_officer': 'Register as Officer',
    'overview.roles_title': 'Sovereign Role Archetypes',
    'overview.roles_subtitle': 'Three streamlined roles aligned with Mission Karmayogi institutional workflows.',
    'overview.learner_title': 'Civil Services Official (Learner)',
    'overview.learner_demo': 'Demo Officer: Rajesh Kumar (Under Secretary)',
    'overview.trainer_title': 'Institutional Trainer & Faculty',
    'overview.trainer_demo': 'Demo Faculty: Dr. Sunita Rao (ISTM)',
    'overview.admin_title': 'Cadre Controlling Authority (Admin)',
    'overview.admin_demo': 'Demo Admin: Cabinet Secretariat / DoPT',
    'overview.welcome_back': 'Welcome back',
    'overview.progress_snapshot': 'Your Progress Snapshot',
    'overview.cadre_score': 'Cadre Competency Score',
    'overview.moderate_deficit': 'Moderate Deficit',
    'overview.explore_rec': 'Explore Recommendations',

    // Common Buttons & Labels
    'btn.submit': 'Submit',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save',
    'btn.close': 'Close',
    'btn.refresh': 'Refresh',
    'status.online': 'ONLINE',
    'status.verified': 'Verified',
  },

  hi: {
    // Top & Brand
    'brand.name': 'एआई कर्मयोगी',
    'brand.sub': 'मिशन कर्मयोगी भारत',
    'brand.motto': 'सत्यमेव जयते • भारत सरकार',
    'brand.ministry': 'कार्मिक, लोक शिकायत और पेंशन मंत्रालय',
    'brand.portal_badge': 'मिशन कर्मयोगी भारत संप्रभु पोर्टल',
    'brand.hero_desc': 'संप्रभु एआई बुद्धिमत्ता द्वारा संचालित सिविल सेवा तत्परता, व्यक्तिगत शिक्षण पथ और योग्यता निदान ढांचे को गति देना।',
    'brand.reach': 'पहुंच',
    'brand.officers_assessed': 'मूल्यांकित एवं शामिल अधिकारी',
    'brand.federal': 'केंद्रीय',
    'brand.ministries_count': 'मंत्रालय एवं राज्य विभाग',
    'brand.models': 'मॉडल',
    'brand.frameworks_count': 'मूल दक्षता रूपरेखा',

    // Navigation
    'nav.overview': 'अवलोकन',
    'nav.assessments': 'मूल्यांकन',
    'nav.recommendations': 'अनुशंसाएँ',
    'nav.learning_path': 'शिक्षण मार्ग',
    'nav.trainer_studio': 'प्रशिक्षक स्टूडियो',
    'nav.certificates': 'प्रमाणपत्र',
    'nav.admin_analytics': 'प्रशासनिक विश्लेषण',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.sign_in': 'साइन इन',
    'nav.register': 'पंजीकरण',
    'nav.sign_out': 'साइन आउट',
    'nav.demo_mode': 'डेमो मोड',
    'nav.my_certificates': 'मेरे सत्यापन योग्य प्रमाणपत्र',
    'nav.cadre_analytics': 'संवर्ग विश्लेषण डैशबोर्ड',
    'nav.officer_profile': 'अधिकारी प्रोफ़ाइल एवं सुरक्षा',

    // Login Form
    'login.title': 'अपने खाते में साइन इन करें',
    'login.subtitle': 'दक्षता निदान तक पहुँचने के लिए अपना आधिकारिक सरकारी ईमेल दर्ज करें',
    'login.email_label': 'आधिकारिक सरकारी ईमेल',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in सत्यापित',
    'login.password_label': 'पासवर्ड',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'पासवर्ड भूल गए?',
    'login.submit_btn': 'कर्मयोगी में साइन इन करें →',
    'login.no_account': 'क्या आपका आधिकारिक खाता नहीं है?',
    'login.register_officer': 'अधिकारी के रूप में पंजीकरण करें',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-क्लिक प्रवेश',
    'login.civil_officer': 'नागरिक अधिकारी',
    'login.learner': 'शिक्षार्थी',
    'login.faculty': 'संकाय',
    'login.trainer': 'प्रशिक्षक',
    'login.director': 'निदेशक',
    'login.admin': 'प्रशासक',
    'login.sovereign_footer': 'संप्रभु स्थानीय स्व-होस्टेड अवसंरचना • MeitY एवं डिजिटल इंडिया प्रमाणित',
    'login.portal_tag': 'सिविल सेवा पोर्टल',
    'login.tier_iv': 'टियर-IV डेटा सेंटर',
    'login.nic_powered': 'राष्ट्रीय सूचना विज्ञान केंद्र (एनआईसी) संप्रभु कंप्यूट क्लस्टर द्वारा संचालित',

    // Overview & Dashboard
    'overview.badge': 'Mission Karmayogi Bharat Sovereign Portal',
    'overview.hero_title': 'एआई-सक्षम दक्षता निदान एवं शिक्षण पारिस्थितिकी तंत्र',
    'overview.hero_desc': 'सिविल सेवा योग्यता अंतरालों का निदान, iGOT कर्मयोगी भंडार के माध्यम से भूमिका-आधारित प्रशिक्षण और आधुनिक भारतीय शासन के लिए स्वचालित मूल्यांकन निर्माण।',
    'overview.sign_in_portal': 'पोर्टल में साइन इन करें',
    'overview.register_officer': 'अधिकारी के रूप में पंजीकरण करें',
    'overview.roles_title': 'संप्रभु भूमिका प्ररूप',
    'overview.roles_subtitle': 'मिशन कर्मयोगी संस्थागत कार्यप्रवाहों के साथ संरेखित तीन सुव्यवस्थित भूमिकाएं।',
    'overview.learner_title': 'सिविल सेवा अधिकारी (शिक्षार्थी)',
    'overview.learner_demo': 'डेमो अधिकारी: राजेश कुमार (अवर सचिव)',
    'overview.trainer_title': 'संस्थागत प्रशिक्षक एवं संकाय',
    'overview.trainer_demo': 'डेमो संकाय: डॉ. सुनीता राव (ISTM)',
    'overview.admin_title': 'संवर्ग नियंत्रण प्राधिकरण (प्रशासक)',
    'overview.admin_demo': 'डेमो व्यवस्थापक: कैबिनेट सचिवालय / डीओपीटी',
    'overview.welcome_back': 'पुनः स्वागत है',
    'overview.progress_snapshot': 'आपकी प्रगति का स्नैपशॉट',
    'overview.cadre_score': 'संवर्ग दक्षता स्कोर',
    'overview.moderate_deficit': 'मध्यम कमी',
    'overview.explore_rec': 'अनुशंसाएँ देखें',

    // Common Buttons & Labels
    'btn.submit': 'जमा करें',
    'btn.cancel': 'रद्द करें',
    'btn.save': 'सहेजें',
    'btn.close': 'बंद करें',
    'btn.refresh': 'रीफ्रेश करें',
    'status.online': 'ऑनलाइन',
    'status.verified': 'सत्यापित',
  },

  ta: {
    // Tamil
    'brand.name': 'AI கர்மயோகி',
    'brand.sub': 'மிஷன் கர்மயோகி பாரத்',
    'brand.motto': 'வாய்மையே வெல்லும் • இந்திய அரசு',
    'brand.ministry': 'பணியாளர், பொதுக் குறைகள் மற்றும் ஓய்வூதிய அமைச்சகம்',
    'brand.portal_badge': 'மிஷன் கர்மயோகி பாரத் இறையாண்மை தளம்',
    'brand.hero_desc': 'திறன் கண்டறிதல் கட்டமைப்புகள், தனிப்பயனாக்கப்பட்ட கற்றல் வழிகள் மற்றும் இறையாண்மை வாய்ந்த AI உளவுத்துறை மூலம் குடிமைப்பணி தயார்நிலையை விரைவுபடுத்துதல்.',
    'brand.reach': 'அளவு',
    'brand.officers_assessed': 'மதிப்பிடப்பட்ட அரசு அதிகாரிகள்',
    'brand.federal': 'ஒன்றியம்',
    'brand.ministries_count': 'அமைச்சகங்கள் மற்றும் துறைகள்',
    'brand.models': 'மாதிரிகள்',
    'brand.frameworks_count': 'முக்கிய திறன் கட்டமைப்புகள்',

    'nav.overview': 'கண்ணோட்டம்',
    'nav.assessments': 'மதிப்பீடுகள்',
    'nav.recommendations': 'பரிந்துரைகள்',
    'nav.learning_path': 'கற்றல் பாதை',
    'nav.trainer_studio': 'பயிற்சியாளர் மையம்',
    'nav.certificates': 'சான்றிதழ்கள்',
    'nav.admin_analytics': 'நிர்வாக பகுப்பாய்வு',
    'nav.profile': 'சுயவிவரம்',
    'nav.sign_in': 'உள்நுழைக',
    'nav.register': 'பதிவுசெய்க',
    'nav.sign_out': 'வெளியேறுக',
    'nav.demo_mode': 'டெமோ முறை',
    'nav.my_certificates': 'சரிபார்க்கக்கூடிய சான்றிதழ்கள்',
    'nav.cadre_analytics': 'பகுப்பாய்வு பலகை',
    'nav.officer_profile': 'அதிகாரி விவரம் & பாதுகாப்பு',

    'login.title': 'உங்கள் கணக்கில் உள்நுழையவும்',
    'login.subtitle': 'திறன் கண்டறிதல்களை அணுக உத்தியோகபூர்வ அரசு மின்னஞ்சலை உள்ளிடவும்',
    'login.email_label': 'உத்தியோகபூர்வ அரசு மின்னஞ்சல்',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in சரிபார்க்கப்பட்டது',
    'login.password_label': 'கடவுச்சொல்',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'login.submit_btn': 'கர்மயோகியில் உள்நுழைக →',
    'login.no_account': 'அதிகாரப்பூர்வ கணக்கு இல்லையா?',
    'login.register_officer': 'அதிகாரியாக பதிவு செய்யுங்கள்',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-கிளிக் தானியங்கி',
    'login.civil_officer': 'குடிமை அதிகாரி',
    'login.learner': 'கற்பவர்',
    'login.faculty': 'ஆசிரியர்',
    'login.trainer': 'பயிற்சியாளர்',
    'login.director': 'இயக்குனர்',
    'login.admin': 'நிர்வாகி',
    'login.sovereign_footer': 'சுய-ஹோஸ்ட் செய்யப்பட்ட இறையாண்மை உள்கட்டமைப்பு • MeitY சான்றளிக்கப்பட்டது',
    'login.portal_tag': 'குடிமைப்பணி தளம்',
    'login.tier_iv': 'TIER-IV தரவு மையம்',
    'login.nic_powered': 'தேசிய தகவலியல் மையம் (NIC) கணினி மூலம் இயக்கப்படுகிறது',

    'btn.submit': 'சமர்ப்பிக்கவும்',
    'btn.cancel': 'ரத்துசெய்',
    'btn.save': 'சேமிக்கவும்',
    'btn.close': 'மூடு',
    'btn.refresh': 'புதுப்பி',
    'status.online': 'இணைப்பில் உள்ளது',
    'status.verified': 'சரிபார்க்கப்பட்டது',
  },

  te: {
    // Telugu
    'brand.name': 'AI కర్మయోగి',
    'brand.sub': 'మిషన్ కర్మయోగి భారత్',
    'brand.motto': 'సత్యమేవ జయతే • భారత ప్రభుత్వం',
    'brand.ministry': 'సిబ్బంది, ప్రజా ఫిర్యాదులు మరియు పెన్షన్ల మంత్రిత్వ శాఖ',
    'brand.portal_badge': 'మిషన్ కర్మయోగి భారత్ సార్వభౌమ పోర్టల్',
    'brand.hero_desc': 'సార్వభౌమ AI ఇంటెలిజెన్స్ ద్వారా సామర్థ్య నిర్ధారణ ఫ్రేమ్‌వర్క్‌లు మరియు సివిల్ సర్వీస్ సన్నద్ధతను వేగవంతం చేయడం.',
    'brand.reach': 'పరిధి',
    'brand.officers_assessed': 'మూల్యాంకనం చేయబడిన అధికారులు',
    'brand.federal': 'కేంద్ర',
    'brand.ministries_count': 'మంత్రిత్వ శాఖలు & విభాగాలు',
    'brand.models': 'మోడల్స్',
    'brand.frameworks_count': 'కోర్ సామర్థ్య ఫ్రేమ్‌వర్క్‌లు',

    'nav.overview': 'అవలోకనం',
    'nav.assessments': 'మూల్యాంకనాలు',
    'nav.recommendations': 'సిఫార్సులు',
    'nav.learning_path': 'అభ్యాస మార్గం',
    'nav.trainer_studio': 'శిక్షకుల స్టూడియో',
    'nav.certificates': 'ధృవీకరణ పత్రాలు',
    'nav.admin_analytics': 'అడ్మిన్ విశ్లేషణలు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.sign_in': 'సైన్ ఇన్',
    'nav.register': 'రిజిస్టర్',
    'nav.sign_out': 'లాగ్ అవుట్',
    'nav.demo_mode': 'డెమో మోడ్',
    'nav.my_certificates': 'నా ధృవీకరణ పత్రాలు',
    'nav.cadre_analytics': 'కేడర్ అనలిటిక్స్ డ్యాష్‌బోర్డ్',
    'nav.officer_profile': 'అధికారి ప్రొఫైల్ & భద్రత',

    'login.title': 'మీ ఖాతాకు సైన్ ఇన్ చేయండి',
    'login.subtitle': 'సామర్థ్య నిర్ధారణలను పొందడానికి అధికారిక ప్రభుత్వ ఇమెయిల్‌ను నమోదు చేయండి',
    'login.email_label': 'అధికారిక ప్రభుత్వ ఇమెయిల్',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in ధృవీకరించబడింది',
    'login.password_label': 'పాస్‌వర్డ్',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'login.submit_btn': 'కర్మయోగికి సైన్ ఇన్ చేయండి →',
    'login.no_account': 'అధికారిక ఖాతా లేదా?',
    'login.register_officer': 'అధికారిగా నమోదు చేసుకోండి',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-క్లిక్ ప్రాప్యత',
    'login.civil_officer': 'సివిల్ అధికారి',
    'login.learner': 'అభ్యాసకుడు',
    'login.faculty': 'ఫ్యాకల్టీ',
    'login.trainer': 'శిక్షకుడు',
    'login.director': 'డైరెక్టర్',
    'login.admin': 'అడ్మిన్',
    'login.sovereign_footer': 'సార్వభౌమ లోకల్ హోస్టెడ్ మౌలిక సదుపాయాలు • MeitY ధృవీకృతం',
    'login.portal_tag': 'సివిల్ సర్వీసెస్ పోర్టల్',
    'login.tier_iv': 'TIER-IV డేటా కేంద్రం',
    'login.nic_powered': 'నేషనల్ ఇన్ఫర్మేటిక్స్ సెంటర్ (NIC) కంప్యూట్ క్లస్టర్ చేత ఆధారితం',

    'btn.submit': 'సమర్పించండి',
    'btn.cancel': 'రద్దు చేయి',
    'btn.save': 'సేవ్ చేయి',
    'btn.close': 'మూసివేయి',
    'btn.refresh': 'రిఫ్రెష్ చేయి',
    'status.online': 'ఆన్‌లైన్',
    'status.verified': 'ధృవీకరించబడింది',
  },

  mr: {
    // Marathi
    'brand.name': 'एआय कर्मयोगी',
    'brand.sub': 'मिशन कर्मयोगी भारत',
    'brand.motto': 'सत्यमेव जयते • भारत सरकार',
    'brand.ministry': 'कार्मिक, सार्वजनिक तक्रारी आणि पेन्शन मंत्रालय',
    'brand.portal_badge': 'मिशन कर्मयोगी भारत सार्वभौम पोर्टल',
    'brand.hero_desc': 'सार्वभौम एआय तंत्रज्ञानाद्वारे संचालित नागरी सेवा सक्षमीकरण आणि क्षमता निदान प्रणाली.',
    'brand.reach': 'व्याप्ती',
    'brand.officers_assessed': 'मूल्यांकन केलेले अधिकारी',
    'brand.federal': 'केंद्रीय',
    'brand.ministries_count': 'मंत्रालये आणि राज्य विभाग',
    'brand.models': 'मॉडेल्स',
    'brand.frameworks_count': 'मूळ क्षमता रूपरेषा',

    'nav.overview': 'आढावा',
    'nav.assessments': 'मूल्यांकन',
    'nav.recommendations': 'शिफारसी',
    'nav.learning_path': 'शिकण्याचा मार्ग',
    'nav.trainer_studio': 'प्रशिक्षक स्टुडिओ',
    'nav.certificates': 'प्रमाणपत्रे',
    'nav.admin_analytics': 'प्रशासकीय विश्लेषण',
    'nav.profile': 'प्रोफाइल',
    'nav.sign_in': 'साइन इन',
    'nav.register': 'नोंदणी करा',
    'nav.sign_out': 'साइन आउट',
    'nav.demo_mode': 'डेमो मोड',
    'nav.my_certificates': 'माझी प्रमाणपत्रे',
    'nav.cadre_analytics': 'विश्लेषण डॅशबोर्ड',
    'nav.officer_profile': 'अधिकारी प्रोफाइल आणि सुरक्षा',

    'login.title': 'आपल्या खात्यात साइन इन करा',
    'login.subtitle': 'क्षमता निदानासाठी आपला अधिकृत शासकीय ईमेल प्रविष्ट करा',
    'login.email_label': 'अधिकृत शासकीय ईमेल',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in पडताळणीकृत',
    'login.password_label': 'पासवर्ड',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'पासवर्ड विसरलात?',
    'login.submit_btn': 'कर्मयोगीमध्ये साइन इन करा →',
    'login.no_account': 'अधिकृत खाते नाही?',
    'login.register_officer': 'अधिकारी म्हणून नोंदणी करा',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-क्लिक प्रवेश',
    'login.civil_officer': 'नागरी अधिकारी',
    'login.learner': 'प्रशिक्षणार्थी',
    'login.faculty': 'प्राध्यापक',
    'login.trainer': 'प्रशिक्षक',
    'login.director': 'संचालक',
    'login.admin': 'प्रशासक',
    'login.sovereign_footer': 'सार्वभौम स्थानिक पायाभूत सुविधा • MeitY प्रमाणित',
    'login.portal_tag': 'नागरी सेवा पोर्टल',
    'login.tier_iv': 'टियर-IV डेटा केंद्र',
    'login.nic_powered': 'राष्ट्रीय माहिती विज्ञान केंद्र (NIC) द्वारे समर्थित',

    'btn.submit': 'प्रस्तुत करा',
    'btn.cancel': 'रद्द करा',
    'btn.save': 'जतन करा',
    'btn.close': 'बंद करा',
    'btn.refresh': 'ताजे करा',
    'status.online': 'ऑनलाइन',
    'status.verified': 'पडताळणीकृत',
  },

  bn: {
    // Bengali
    'brand.name': 'এআই কর্মযোগী',
    'brand.sub': 'মিশন কর্মযোগী ভারত',
    'brand.motto': 'সত্যমেব জয়তে • ভারত সরকার',
    'brand.ministry': 'কর্মী, জনঅভিযোগ ও পেনশন মন্ত্রক',
    'brand.portal_badge': 'মিশন কর্মযোগী ভারত সার্বভৌম পোর্টাল',
    'brand.hero_desc': 'সার্বভৌম এআই প্রযুক্তি দ্বারা সিভিল সার্ভিসের দক্ষতা নির্ণয় এবং আধুনিক প্রশাসনিক প্রশিক্ষণ ত্বরান্বিত করা।',
    'brand.reach': 'পরিধি',
    'brand.officers_assessed': 'মূল্যায়িত সরকারি আধিকারিক',
    'brand.federal': 'যুক্তরাষ্ট্রীয়',
    'brand.ministries_count': 'মন্ত্রক ও রাজ্য দপ্তর',
    'brand.models': 'মডেল',
    'brand.frameworks_count': 'মূল দক্ষতা কাঠামো',

    'nav.overview': 'সংক্ষিপ্ত বিবরণ',
    'nav.assessments': 'মূল্যায়ন',
    'nav.recommendations': 'সুপারিশ',
    'nav.learning_path': 'শিক্ষণ পথ',
    'nav.trainer_studio': 'প্রশিক্ষক স্টুডিও',
    'nav.certificates': 'শংসাপত্র',
    'nav.admin_analytics': 'প্রশাসনিক বিশ্লেষণ',
    'nav.profile': 'প্রোফাইল',
    'nav.sign_in': 'সাইন ইন',
    'nav.register': 'নিবন্ধন',
    'nav.sign_out': 'সাইন আউট',
    'nav.demo_mode': 'ডেমো মোড',
    'nav.my_certificates': 'যাচাইযোগ্য শংসাপত্র',
    'nav.cadre_analytics': 'ক্যাডার বিশ্লেষণ ড্যাশবোর্ড',
    'nav.officer_profile': 'আধিকারিক প্রোফাইল ও নিরাপত্তা',

    'login.title': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'login.subtitle': 'দক্ষতা মূল্যায়নের জন্য অফিশিয়াল সরকারি ইমেল প্রবেশ করান',
    'login.email_label': 'অফিশিয়াল সরকারি ইমেল',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in যাচাইকৃত',
    'login.password_label': 'পাসওয়ার্ড',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'login.submit_btn': 'কর্মযোগীতে সাইন ইন করুন →',
    'login.no_account': 'অফিশিয়াল অ্যাকাউন্ট নেই?',
    'login.register_officer': 'আধিকারিক হিসেবে নিবন্ধন করুন',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '১-ক্লিক প্রমাণীকরণ',
    'login.civil_officer': 'সিভিল অফিসার',
    'login.learner': 'শিক্ষার্থী',
    'login.faculty': 'অনুষদ',
    'login.trainer': 'প্রশিক্ষক',
    'login.director': 'অধ্যক্ষ',
    'login.admin': 'প্রশাসক',
    'login.sovereign_footer': 'সার্বভৌম স্থানীয় ক্লাউড পরিকাঠামো • MeitY স্বীকৃত',
    'login.portal_tag': 'সিভিল সার্ভিস পোর্টাল',
    'login.tier_iv': 'টিয়ার-৪ ডেটা সেন্টার',
    'login.nic_powered': 'জাতীয় তথ্যবিজ্ঞান কেন্দ্র (NIC) দ্বারা পরিচালিত',

    'btn.submit': 'জমা দিন',
    'btn.cancel': 'বাতিল',
    'btn.save': 'সংরক্ষণ করুন',
    'btn.close': 'বন্ধ করুন',
    'btn.refresh': 'রিফ্রেশ',
    'status.online': 'অনলাইন',
    'status.verified': 'যাচাইকৃত',
  },

  gu: {
    // Gujarati
    'brand.name': 'AI કર્મયોગી',
    'brand.sub': 'મિશન કર્મયોગી ભારત',
    'brand.motto': 'સત્યમેવ જયતે • ભારત સરકાર',
    'brand.ministry': 'કર્મચારી, જાહેર ફરિયાદ અને પેન્શન મંત્રાલય',
    'brand.portal_badge': 'મિશન કર્મયોગી ભારત સાર્વભૌમ પોર્ટલ',
    'brand.hero_desc': 'સાર્વભૌમ એઆઈ બુદ્ધિ દ્વારા સિવિલ સર્વિસ યોગ્યતા નિદાન અને તાલીમ પ્રક્રિયાને ઝડપી બનાવવી.',
    'brand.reach': 'પહોંચ',
    'brand.officers_assessed': 'મૂલ્યાંકન કરેલ અધિકારીઓ',
    'brand.federal': 'ફેડરલ',
    'brand.ministries_count': 'મંત્રાલયો અને રાજ્ય વિભાગો',
    'brand.models': 'મોડેલ્સ',
    'brand.frameworks_count': 'મુખ્ય ક્ષમતા ફ્રેમવર્ક',

    'nav.overview': 'ઝાંખી',
    'nav.assessments': 'મૂલ્યાંકન',
    'nav.recommendations': 'ભલામણો',
    'nav.learning_path': 'શિક્ષણ માર્ગ',
    'nav.trainer_studio': 'ટ્રેનર સ્ટુડિયો',
    'nav.certificates': 'પ્રમાણપત્રો',
    'nav.admin_analytics': 'એડમિન એનાલિટિક્સ',
    'nav.profile': 'પ્રોફાઇલ',
    'nav.sign_in': 'સાઇન ઇન',
    'nav.register': 'નોંધણી કરો',
    'nav.sign_out': 'સાઇન આઉટ',
    'nav.demo_mode': 'ડેમો મોડ',
    'nav.my_certificates': 'મારા પ્રમાણપત્રો',
    'nav.cadre_analytics': 'કેડર એનાલિટિક્સ',
    'nav.officer_profile': 'અધિકારી પ્રોફાઇલ અને સુરક્ષા',

    'login.title': 'તમારા ખાતામાં સાઇન ઇન કરો',
    'login.subtitle': 'યોગ્યતા નિદાન માટે તમારું સત્તાવાર સરકારી ઇમેઇલ દાખલ કરો',
    'login.email_label': 'સત્તાવાર સરકારી ઇમેઇલ',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in પ્રમાણિત',
    'login.password_label': 'પાસવર્ડ',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'પાસવર્ડ ભૂલી ગયા છો?',
    'login.submit_btn': 'કર્મયોગીમાં સાઇન ઇન કરો →',
    'login.no_account': 'સત્તાવાર એકાઉન્ટ નથી?',
    'login.register_officer': 'અધિકારી તરીકે નોંધણી કરો',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '૧-ક્લિક પ્રમાણીકરણ',
    'login.civil_officer': 'સિવિલ ઓફિસર',
    'login.learner': 'શીખનાર',
    'login.faculty': 'ફેકલ્ટી',
    'login.trainer': 'ટ્રેનર',
    'login.director': 'ડિરેક્ટર',
    'login.admin': 'એડમિન',
    'login.sovereign_footer': 'સાર્વભૌમ સ્થાનિક ઇન્ફ્રાસ્ટ્રક્ચર • MeitY પ્રમાણિત',
    'login.portal_tag': 'સિવિલ સર્વિસીસ પોર્ટલ',
    'login.tier_iv': 'TIER-IV ડેટા સેન્ટર',
    'login.nic_powered': 'નેશનલ ઇન્ફોર્મેટિક્સ સેન્ટર (NIC) દ્વારા સંચાલિત',

    'btn.submit': 'સબમિટ કરો',
    'btn.cancel': 'રદ કરો',
    'btn.save': 'સાચવો',
    'btn.close': 'બંધ કરો',
    'btn.refresh': 'રીફ્રેશ કરો',
    'status.online': 'ઓનલાઇન',
    'status.verified': 'ચકાસાયેલ',
  },

  kn: {
    // Kannada
    'brand.name': 'AI ಕರ್ಮಯೋಗಿ',
    'brand.sub': 'ಮಿಷನ್ ಕರ್ಮಯೋಗಿ ಭಾರತ್',
    'brand.motto': 'ಸತ್ಯಮೇವ ಜಯತೆ • ಭಾರತ ಸರ್ಕಾರ',
    'brand.ministry': 'ಸಿಬ್ಬಂದಿ, ಸಾರ್ವಜನಿಕ ಕುಂದುಕೊರತೆ ಮತ್ತು ಪಿಂಚಣಿ ಸಚಿವಾಲಯ',
    'brand.portal_badge': 'ಮಿಷನ್ ಕರ್ಮಯೋಗಿ ಭಾರತ್ ಸಾರ್ವಭೌಮ ಪೋರ್ಟಲ್',
    'brand.hero_desc': 'ಸಾರ್ವಭೌಮ AI ಬುದ್ಧಿಮತ್ತೆಯೊಂದಿಗೆ ನಾಗರಿಕ ಸೇವೆಗಳ ಸಾಮರ್ಥ್ಯ ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ತರಬೇತಿಯನ್ನು ವೇಗಗೊಳಿಸುವುದು.',
    'brand.reach': 'ವ್ಯಾಪ್ತಿ',
    'brand.officers_assessed': 'ಮೌಲ್ಯಮಾಪನಗೊಂಡ ಅಧಿಕಾರಿಗಳು',
    'brand.federal': 'ಕೇಂದ್ರ',
    'brand.ministries_count': 'ಸಚಿವಾಲಯಗಳು ಮತ್ತು ಇಲಾಖೆಗಳು',
    'brand.models': 'ಮಾದರಿಗಳು',
    'brand.frameworks_count': 'ಸಾಮರ್ಥ್ಯ ಚೌಕಟ್ಟುಗಳು',

    'nav.overview': 'ಅವಲೋಕನ',
    'nav.assessments': 'ಮೌಲ್ಯಮಾಪನಗಳು',
    'nav.recommendations': 'ಶಿಫಾರಸುಗಳು',
    'nav.learning_path': 'ಕಲಿಕೆಯ ಮಾರ್ಗ',
    'nav.trainer_studio': 'ತರಬೇತುದಾರ ಸ್ಟುಡಿಯೋ',
    'nav.certificates': 'ಪ್ರಮಾಣಪತ್ರಗಳು',
    'nav.admin_analytics': 'ಆಡಳಿತ ವಿಶ್ಲೇಷಣೆ',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'nav.sign_in': 'ಸೈನ್ ಇನ್',
    'nav.register': 'ನೋಂದಣಿ',
    'nav.sign_out': 'ಸೈನ್ ಔಟ್',
    'nav.demo_mode': 'ಡೆಮೊ ಮೋಡ್',
    'nav.my_certificates': 'ನನ್ನ ಪ್ರಮಾಣಪತ್ರಗಳು',
    'nav.cadre_analytics': 'ವಿಶ್ಲೇಷಣೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.officer_profile': 'ಅಧಿಕಾರಿ ಪ್ರೊಫೈಲ್ & ಭದ್ರತೆ',

    'login.title': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.subtitle': 'ಸಾಮರ್ಥ್ಯ ಪರೀಕ್ಷೆಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'login.email_label': 'ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಇಮೇಲ್',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'login.password_label': 'ಪಾಸ್‌ವರ್ಡ್',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    'login.submit_btn': 'ಕರ್ಮಯೋಗಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ →',
    'login.no_account': 'ಅಧಿಕೃತ ಖಾತೆ ಇಲ್ಲವೇ?',
    'login.register_officer': 'ಅಧಿಕಾರಿಯಾಗಿ ನೋಂದಾಯಿಸಿ',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-ಕ್ಲಿಕ್ ದೃಢೀಕರಣ',
    'login.civil_officer': 'ನಾಗರಿಕ ಅಧಿಕಾರಿ',
    'login.learner': 'ಕಲಿಯುವವರು',
    'login.faculty': 'ಅಧ್ಯಾಪಕರು',
    'login.trainer': 'ತರಬೇತುದಾರ',
    'login.director': 'ನಿರ್ದೇಶಕ',
    'login.admin': 'ನಿರ್ವಾಹಕ',
    'login.sovereign_footer': 'ಸಾರ್ವಭೌಮ ಸ್ಥಳೀಯ ಮೂಲಸೌಕರ್ಯ • MeitY ಪ್ರಮಾಣೀಕೃತ',
    'login.portal_tag': 'ನಾಗರಿಕ ಸೇವೆಗಳ ಪೋರ್ಟಲ್',
    'login.tier_iv': 'TIER-IV ಡೇಟಾ ಸೆಂಟರ್',
    'login.nic_powered': 'ನ್ಯಾಷನಲ್ ಇನ್ಫರ್ಮ್ಯಾಟಿಕ್ಸ್ ಸೆಂಟರ್ (NIC) ಚಾಲಿತ',

    'btn.submit': 'ಸಲ್ಲಿಸಿ',
    'btn.cancel': 'ರದ್ದುಮಾಡಿ',
    'btn.save': 'ಉಳಿಸಿ',
    'btn.close': 'ಮುಚ್ಚಿ',
    'btn.refresh': 'ನವೀಕರಿಸಿ',
    'status.online': 'ಆನ್‌ಲೈನ್',
    'status.verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  },

  ml: {
    // Malayalam
    'brand.name': 'AI കർമ്മയോഗി',
    'brand.sub': 'മിഷൻ കർമ്മയോഗി ഭാരത്',
    'brand.motto': 'സത്യമേവ ജയതേ • ഭാരത സർക്കാർ',
    'brand.ministry': 'പേഴ്സണൽ, പൊതു പരാതി, പെൻഷൻ മന്ത്രാലയം',
    'brand.portal_badge': 'മിഷൻ കർമ്മയോഗി ഭാരത് പോർട്ടൽ',
    'brand.hero_desc': 'സിവിൽ സർവീസ് കാര്യക്ഷമതയും ശേഷി വികസനവും വേഗത്തിലാക്കുന്ന എഐ പ്ലാറ്റ്‌ഫോം.',
    'brand.reach': 'വ്യാപ്തി',
    'brand.officers_assessed': 'വിലയിരുത്തിയ ഉദ്യോഗസ്ഥർ',
    'brand.federal': 'കേന്ദ്ര',
    'brand.ministries_count': 'മന്ത്രാലയങ്ങളും വകുപ്പുകളും',
    'brand.models': 'മാതൃകകൾ',
    'brand.frameworks_count': 'പ്രധാന ശേഷി ചട്ടക്കൂടുകൾ',

    'nav.overview': 'അവലോകനം',
    'nav.assessments': 'മൂല്യനിർണ്ണയങ്ങൾ',
    'nav.recommendations': 'ശുപാർശകൾ',
    'nav.learning_path': 'പഠന പാത',
    'nav.trainer_studio': 'ട്രെയിനർ സ്റ്റുഡിയോ',
    'nav.certificates': 'സർട്ടിഫിക്കറ്റുകൾ',
    'nav.admin_analytics': 'അഡ്മിൻ അനലിറ്റിക്സ്',
    'nav.profile': 'പ്രൊഫൈൽ',
    'nav.sign_in': 'സൈൻ ഇൻ',
    'nav.register': 'രജിസ്റ്റർ ചെയ്യുക',
    'nav.sign_out': 'സൈൻ ഔട്ട്',
    'nav.demo_mode': 'ഡെമോ മോഡ്',
    'nav.my_certificates': 'എന്റെ സർട്ടിഫിക്കറ്റുകൾ',
    'nav.cadre_analytics': 'അനലിറ്റിക്സ് ഡാഷ്‌ബോർഡ്',
    'nav.officer_profile': 'ഉദ്യോഗസ്ഥ പ്രൊഫൈൽ & സുരക്ഷ',

    'login.title': 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക',
    'login.subtitle': 'ഔദ്യോഗിക സർക്കാർ ഇമെയിൽ നൽകുക',
    'login.email_label': 'ഔദ്യോഗിക സർക്കാർ ഇമെയിൽ',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in പരിശോധിച്ചുറപ്പിച്ചു',
    'login.password_label': 'പാസ്‌വേഡ്',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
    'login.submit_btn': 'കർമ്മയോഗിയിൽ സൈൻ ഇൻ ചെയ്യുക →',
    'login.no_account': 'ഔദ്യോഗിക അക്കൗണ്ട് ഇല്ലേ?',
    'login.register_officer': 'ഉദ്യോഗസ്ഥനായി രജിസ്റ്റർ ചെയ്യുക',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-ക്ലിക്ക് പ്രവേശനം',
    'login.civil_officer': 'സിവിൽ ഓഫീസർ',
    'login.learner': 'പഠിതാവ്',
    'login.faculty': 'ഫാക്കൽറ്റി',
    'login.trainer': 'ട്രെയിനർ',
    'login.director': 'ഡയറക്ടർ',
    'login.admin': 'അഡ്മിൻ',
    'login.sovereign_footer': 'സ്വയം ഹോസ്റ്റ് ചെയ്ത പ്രാദേശിക ഇൻഫ്രാസ്ട്രക്ചർ • MeitY സാക്ഷ്യപ്പെടുത്തിയത്',
    'login.portal_tag': 'സിവിൽ സർവീസസ് പോർട്ടൽ',
    'login.tier_iv': 'TIER-IV ഡാറ്റാ സെന്റർ',
    'login.nic_powered': 'നാഷണൽ ഇൻഫോർമാറ്റിക്സ് സെന്റർ (NIC) പ്രവർത്തിപ്പിക്കുന്നത്',

    'btn.submit': 'സമർപ്പിക്കുക',
    'btn.cancel': 'റദ്ദാക്കുക',
    'btn.save': 'സംരക്ഷിക്കുക',
    'btn.close': 'അടയ്ക്കുക',
    'btn.refresh': 'പുതുക്കുക',
    'status.online': 'ഓൺലൈൻ',
    'status.verified': 'സ്ഥിരീകരിച്ചു',
  },

  pa: {
    // Punjabi
    'brand.name': 'AI ਕਰਮਯੋਗੀ',
    'brand.sub': 'ਮਿਸ਼ਨ ਕਰਮਯੋਗੀ ਭਾਰਤ',
    'brand.motto': 'ਸਤਯਮੇਵ ਜਯਤੇ • ਭਾਰਤ ਸਰਕਾਰ',
    'brand.ministry': 'ਪ੍ਰਸੋਨਲ, ਲੋਕ ਸ਼ਿਕਾਇਤਾਂ ਅਤੇ ਪੈਨਸ਼ਨ ਮੰਤਰਾਲਾ',
    'brand.portal_badge': 'ਮਿਸ਼ਨ ਕਰਮਯੋਗੀ ਭਾਰਤ ਪ੍ਰਭੂਸੱਤਾ ਪੋਰਟਲ',
    'brand.hero_desc': 'ਸਿਵਲ ਸੇਵਾਵਾਂ ਸਮਰੱਥਾ ਨਿਰਧਾਰਨ ਅਤੇ ਵਿਅਕਤੀਗਤ ਸਿਖਲਾਈ ਪਲੇਟਫਾਰਮ।',
    'brand.reach': 'ਪਹੁੰਚ',
    'brand.officers_assessed': 'ਮੁਲਾਂਕਣ ਕੀਤੇ ਅਧਿਕਾਰੀ',
    'brand.federal': 'ਕੇਂਦਰੀ',
    'brand.ministries_count': 'ਮੰਤਰਾਲੇ ਅਤੇ ਵਿਭਾਗ',
    'brand.models': 'ਮਾਡਲ',
    'brand.frameworks_count': 'ਮੁੱਖ ਯੋਗਤਾ ਢਾਂਚੇ',

    'nav.overview': 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    'nav.assessments': 'ਮੁਲਾਂਕਣ',
    'nav.recommendations': 'ਸਿਫ਼ਾਰਸ਼ਾਂ',
    'nav.learning_path': 'ਸਿੱਖਣ ਮਾਰਗ',
    'nav.trainer_studio': 'ਟ੍ਰੇਨਰ ਸਟੂਡੀਓ',
    'nav.certificates': 'ਸਰਟੀਫਿਕੇਟ',
    'nav.admin_analytics': 'ਪ੍ਰਬੰਧਕੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'nav.sign_in': 'ਸਾਈਨ ਇਨ',
    'nav.register': 'ਰਜਿਸਟਰ',
    'nav.sign_out': 'ਸਾਈਨ ਆਉਟ',
    'nav.demo_mode': 'ਡੈਮੋ ਮੋਡ',
    'nav.my_certificates': 'ਮੇਰੇ ਪ੍ਰਮਾਣ ਪੱਤਰ',
    'nav.cadre_analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ ਡੈਸ਼ਬੋਰਡ',
    'nav.officer_profile': 'ਅਧਿਕਾਰੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੁਰੱਖਿਆ',

    'login.title': 'ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
    'login.subtitle': 'ਯੋਗਤਾ ਨਿਰਧਾਰਨ ਲਈ ਆਪਣਾ ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਈਮੇਲ ਦਰਜ ਕਰੋ',
    'login.email_label': 'ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਈਮੇਲ',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in ਤਸਦੀਕਸ਼ੁਦਾ',
    'login.password_label': 'ਪਾਸਵਰਡ',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    'login.submit_btn': 'ਕਰਮਯੋਗੀ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ →',
    'login.no_account': 'ਕੀ ਅਧਿਕਾਰਤ ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    'login.register_officer': 'ਅਧਿਕਾਰੀ ਵਜੋਂ ਰਜਿਸਟਰ ਕਰੋ',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '1-ਕਲਿੱਕ ਪ੍ਰਵੇਸ਼',
    'login.civil_officer': 'ਸਿਵਲ ਅਧਿਕਾਰੀ',
    'login.learner': 'ਸਿੱਖਣ ਵਾਲਾ',
    'login.faculty': 'ਫੈਕਲਟੀ',
    'login.trainer': 'ਟ੍ਰੇਨਰ',
    'login.director': 'ਡਾਇਰੈਕਟਰ',
    'login.admin': 'ਪ੍ਰਬੰਧਕ',
    'login.sovereign_footer': 'ਪ੍ਰਭੂਸੱਤਾ ਸੰਪੰਨ ਸਥਾਨਕ ਬੁਨਿਆਦੀ ਢਾਂਚਾ • MeitY ਪ੍ਰਮਾਣਿਤ',
    'login.portal_tag': 'ਸਿਵਲ ਸੇਵਾਵਾਂ ਪੋਰਟਲ',
    'login.tier_iv': 'TIER-IV ਡਾਟਾ ਸੈਂਟਰ',
    'login.nic_powered': 'ਨੈਸ਼ਨਲ ਇਨਫਾਰਮੈਟਿਕਸ ਸੈਂਟਰ (NIC) ਦੁਆਰਾ ਸੰਚਾਲਿਤ',

    'btn.submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
    'btn.cancel': 'ਰੱਦ ਕਰੋ',
    'btn.save': 'ਸੰਭਾਲੋ',
    'btn.close': 'ਬੰਦ ਕਰੋ',
    'btn.refresh': 'ਤਾਜ਼ਾ ਕਰੋ',
    'status.online': 'ਆਨਲਾਈਨ',
    'status.verified': 'ਤਸਦੀਕਸ਼ੁਦਾ',
  },

  or: {
    // Odia
    'brand.name': 'AI କର୍ମଯୋଗୀ',
    'brand.sub': 'ମିଶନ କର୍ମଯୋଗୀ ଭାରତ',
    'brand.motto': 'ସତ୍ୟମେବ ଜୟତେ • ଭାରତ ସରକାର',
    'brand.ministry': 'କର୍ମଚାରୀ, ଜନ ଅଭିଯୋଗ ଏବଂ ପେନସନ ମନ୍ତ୍ରଣାଳୟ',
    'brand.portal_badge': 'ମିଶନ କର୍ମଯୋଗୀ ଭାରତ ସାର୍ବଭୌମ ପୋର୍ଟାଲ',
    'brand.hero_desc': 'ସିଭିଲ ସେବା ଦକ୍ଷତା ମୂଲ୍ୟାୟନ ଏବଂ ପ୍ରଶିକ୍ଷଣ ପ୍ରଣାଳୀ।',
    'brand.reach': 'ପରିସୀମା',
    'brand.officers_assessed': 'ମୂଲ୍ୟାଙ୍କିତ ଅଧିକାରୀ',
    'brand.federal': 'କେନ୍ଦ୍ରୀୟ',
    'brand.ministries_count': 'ମନ୍ତ୍ରଣାଳୟ ଏବଂ ବିଭାଗ',
    'brand.models': 'ମଡେଲ',
    'brand.frameworks_count': 'ଦକ୍ଷତା ଢାଞ୍ଚା',

    'nav.overview': 'ସମୀକ୍ଷା',
    'nav.assessments': 'ମୂଲ୍ୟାୟନ',
    'nav.recommendations': 'ପରାମର୍ଶ',
    'nav.learning_path': 'ଶିକ୍ଷଣ ପଥ',
    'nav.trainer_studio': 'ପ୍ରଶିକ୍ଷକ ଷ୍ଟୁଡିଓ',
    'nav.certificates': 'ପ୍ରମାଣପତ୍ର',
    'nav.admin_analytics': 'ପ୍ରଶାସନିକ ବିଶ୍ଳେଷଣ',
    'nav.profile': 'ପ୍ରୋଫାଇଲ୍',
    'nav.sign_in': 'ସାଇନ୍ ଇନ୍',
    'nav.register': 'ପଞ୍ଜୀକରଣ',
    'nav.sign_out': 'ସାଇନ୍ ଆଉଟ୍',
    'nav.demo_mode': 'ଡେମୋ ମୋଡ୍',
    'nav.my_certificates': 'ମୋର ପ୍ରମାଣପତ୍ର',
    'nav.cadre_analytics': 'ବିଶ୍ଳେଷଣ ଡ୍ୟାସବୋର୍ଡ',
    'nav.officer_profile': 'ଅଧିକାରୀ ପ୍ରୋଫାଇଲ୍ ଏବଂ ସୁରକ୍ଷା',

    'login.title': 'ଆପଣଙ୍କ ଖାତାରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
    'login.subtitle': 'ଦକ୍ଷତା ନିର୍ଣ୍ଣୟ ପାଇଁ ଆପଣଙ୍କ ସରକାରୀ ଇମେଲ୍ ପ୍ରବେଶ କରନ୍ତୁ',
    'login.email_label': 'ଅଫିସିଆଲ୍ ସରକାରୀ ଇମେଲ୍',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in ଯାଞ୍ଚ ହୋଇଛି',
    'login.password_label': 'ପାସୱାର୍ଡ',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?',
    'login.submit_btn': 'କର୍ମଯୋଗୀରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ →',
    'login.no_account': 'କୌଣସି ଅଫିସିଆଲ୍ ଆକାଉଣ୍ଟ୍ ନାହିଁ କି?',
    'login.register_officer': 'ଅଧିକାରୀ ଭାବରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '୧-କ୍ଲିକ୍ ପ୍ରବେଶ',
    'login.civil_officer': 'ସିଭିଲ୍ ଅଫିସର',
    'login.learner': 'ଶିକ୍ଷାର୍ଥୀ',
    'login.faculty': 'ଅଧ୍ୟାପକ',
    'login.trainer': 'ପ୍ରଶିକ୍ଷକ',
    'login.director': 'ନିର୍ଦ୍ଦେଶକ',
    'login.admin': 'ପ୍ରଶାସକ',
    'login.sovereign_footer': 'ସ୍ୱୟଂ ହୋଷ୍ଟ ହୋଇଥିବା ସାର୍ବଭୌମ ଭିତ୍ତିଭୂମି • MeitY ପ୍ରମାଣିତ',
    'login.portal_tag': 'ସିଭିଲ ସର୍ଭିସେସ୍ ପୋର୍ଟାଲ',
    'login.tier_iv': 'TIER-IV ଡାଟା ସେଣ୍ଟର',
    'login.nic_powered': 'ଜାତୀୟ ସୂଚନା ବିଜ୍ଞାନ କେନ୍ଦ୍ର (NIC) ଦ୍ୱାରା ପରିଚାଳିତ',

    'btn.submit': 'ଦାଖଲ କରନ୍ତୁ',
    'btn.cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
    'btn.save': 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    'btn.close': 'ବନ୍ଦ କରନ୍ତୁ',
    'btn.refresh': 'ରିଫ୍ରେସ୍',
    'status.online': 'ଅନଲାଇନ୍',
    'status.verified': 'ଯାଞ୍ଚ ହୋଇଛି',
  },

  as: {
    // Assamese
    'brand.name': 'এআই কৰ্মযোগী',
    'brand.sub': 'মিছন কৰ্মযোগী ভাৰত',
    'brand.motto': 'সত্যমেৱ জয়তে • ভাৰত চৰকাৰ',
    'brand.ministry': 'কৰ্মচাৰী, ৰাজহুৱা ওজৰ-আপত্তি আৰু পেঞ্চন মন্ত্ৰালয়',
    'brand.portal_badge': 'মিছন কৰ্মযোগী ভাৰত সাৰ্বভৌম পৰ্টেল',
    'brand.hero_desc': 'চিভিল সেৱাৰ দক্ষতা নিৰ্ধাৰণ আৰু প্ৰশিক্ষণৰ সাৰ্বভৌম এআই মঞ্চ।',
    'brand.reach': 'পৰিধি',
    'brand.officers_assessed': 'মূল্যায়িত বিষয়া',
    'brand.federal': 'যুক্তৰাষ্ট্ৰীয়',
    'brand.ministries_count': 'মন্ত্ৰালয় আৰু বিভাগ',
    'brand.models': 'মডেল',
    'brand.frameworks_count': 'মূল দক্ষতা কাঠামো',

    'nav.overview': 'অৱলোকন',
    'nav.assessments': 'মূল্যায়ন',
    'nav.recommendations': 'পৰামৰ্শ',
    'nav.learning_path': 'শিক্ষণ পথ',
    'nav.trainer_studio': 'প্ৰশিক্ষক ষ্টুডিঅ’',
    'nav.certificates': 'প্ৰমাণপত্ৰ',
    'nav.admin_analytics': 'প্ৰশাসনিক বিশ্লেষণ',
    'nav.profile': 'প্ৰফাইল',
    'nav.sign_in': 'ছাইন ইন',
    'nav.register': 'পঞ্জীয়ন',
    'nav.sign_out': 'ছাইন আউট',
    'nav.demo_mode': 'ডেমো ম’ড',
    'nav.my_certificates': 'মোৰ প্ৰমাণপত্ৰ',
    'nav.cadre_analytics': 'বিশ্লেষণ ডেচব’ৰ্ড',
    'nav.officer_profile': 'বিষয়া প্ৰফাইল আৰু সুৰক্ষা',

    'login.title': 'আপোনাৰ একাউণ্টত ছাইন ইন কৰক',
    'login.subtitle': 'দক্ষতা পৰীক্ষাৰ বাবে চৰকাৰী ইমেইল দিয়ক',
    'login.email_label': 'চৰকাৰী ইমেইল',
    'login.email_placeholder': 'rajesh.kumar@gov.in',
    'login.email_verified': '.gov.in / .nic.in প্ৰমাণিত',
    'login.password_label': 'পাছৱৰ্ড',
    'login.password_placeholder': '••••••••••••',
    'login.forgot_password': 'পাছৱৰ্ড পাহৰিলে নেকি?',
    'login.submit_btn': 'কৰ্মযোগীত ছাইন ইন কৰক →',
    'login.no_account': 'চৰকাৰী একাউণ্ট নাই নেকি?',
    'login.register_officer': 'বিষয়া হিচাপে পঞ্জীয়ন কৰক',
    'login.quick_logins': 'Quick Logins:',
    'login.one_click': '১-ক্লিক প্ৰৱেশ',
    'login.civil_officer': 'অসামৰিক বিষয়া',
    'login.learner': 'শিক্ষাৰ্থী',
    'login.faculty': 'শিক্ষক',
    'login.trainer': 'প্ৰশিক্ষক',
    'login.director': 'সঞ্চালক',
    'login.admin': 'প্ৰশাসক',
    'login.sovereign_footer': 'সাৰ্বভৌম স্থানীয় আন্তঃগাঁথনি • MeitY প্ৰমাণিত',
    'login.portal_tag': 'অসামৰিক সেৱা পৰ্টেল',
    'login.tier_iv': 'TIER-IV তথ্য কেন্দ্ৰ',
    'login.nic_powered': 'ৰাষ্ট্ৰীয় তথ্যবিজ্ঞান কেন্দ্ৰ (NIC) দ্বাৰা পৰিচালিত',

    'btn.submit': 'দাখিল কৰক',
    'btn.cancel': 'বাতিল কৰক',
    'btn.save': 'সংৰক্ষণ কৰক',
    'btn.close': 'বন্ধ কৰক',
    'btn.refresh': 'পুনৰ সতেজ কৰক',
    'status.online': 'অনলাইন',
    'status.verified': 'প্ৰমাণিত',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('karmayogi_lang') as SupportedLanguage;
    if (saved && TRANSLATIONS[saved]) return saved;
    return 'en';
  });

  const setLanguage = (newLang: SupportedLanguage) => {
    if (TRANSLATIONS[newLang]) {
      setLanguageState(newLang);
      localStorage.setItem('karmayogi_lang', newLang);
      // Set HTML lang attribute
      document.documentElement.lang = newLang;
    }
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const currentDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (currentDict[key]) return currentDict[key];
    if (TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
